version: '3.3'
services:
  nextcloud-db:
    image: lscr.io/linuxserver/mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - '${DIR}/database-config:/config'
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MARIA_DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MARIA_DB_NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=${MARIA_DB_NEXTCLOUD_DATABASE}
      - MYSQL_USER=${MARIA_DB_NEXTCLOUD_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1
    networks:
      - internal
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    networks:
      - internal
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
  nextcloud-app:
    build:
      context: https://github.com/panic175/nextcloud-pi.git
    container_name: nextcloud-app
    environment:
      - PUID=1000
      - PGID=1000
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - MYSQL_HOST=nextcloud-db:3306
      - MYSQL_PASSWORD=${MARIA_DB_NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=${MARIA_DB_NEXTCLOUD_DATABASE}
      - MYSQL_USER=${MARIA_DB_NEXTCLOUD_USER}
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - '${DIR}/main:/var/www/html'
      - '${DIR}/apps:/var/www/html/custom_apps'
      - '${DIR}/config:/var/www/html/config'
      - '${DIR}/data:/var/www/html/data'
      - '${DIR}/theme:/var/www/html/themes'
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    restart: unless-stopped
    ports:
      - "${NEXTCLOUD_HTTP_PORT}:80"
    networks:
      - web
      - internal
networks:
  web:
    external: true
  internal:
    external: false